"use client"

import { useState } from "react"
import { ArrowLeft, ArrowRight, Check, Clock3, MapPin } from "lucide-react"
import { AppShell, GlowCard, Link, PageFooter, Reveal, StatusPill } from "@/components/travel-ui"

const results = [{ title: "Bandra by twilight", meta: "WALK · 2H 40M", copy: "A sea-facing pause, a quiet table, and enough room for the evening to unfold.", why: "It keeps you within 18 minutes of your reservation and leaves a 28-minute buffer.", status: "pass" as const }, { title: "Old city, slow streets", meta: "METRO · 3H 15M", copy: "Small lanes, warm light, and a route that knows when to stop asking for more.", why: "The route is direct, mostly shaded, and fits the longer version of your window.", status: "pass" as const }, { title: "Kanheri Caves", meta: "CAB · 4H 20M", copy: "A beautiful route through the green north of the city.", why: "The last return bus leaves before your dinner reservation, so this one does not fit today.", status: "fail" as const, reason: "returns 35 minutes after your reservation" }]

export default function DiscoverPage() { const [open, setOpen] = useState<number | null>(0); return <AppShell><div className="discover-page app-page"><div className="app-topline"><Link href="/"><ArrowLeft size={14} /> HOME</Link><span>DISCOVERY / 01</span><Link href="/plan">VIEW PLAN <ArrowRight size={14} /></Link></div><Reveal><div className="discover-intro"><p className="eyebrow">SATURDAY 17 AUG · MUMBAI</p><h1>Places that<br /><i>fit the day.</i></h1><p className="discover-copy">Three options survived the gate. The rest were honest no&apos;s.</p></div></Reveal><div className="results">{results.map((result, index) => <Reveal key={result.title} delay={index * 85}><GlowCard className="result-card"><span className="result-number">0{index + 1}</span><div className="result-main"><div className="result-meta"><span><Clock3 size={12} /> {result.meta}</span><span><MapPin size={12} /> MUMBAI</span></div><h2>{result.title}</h2><p>{result.copy}</p><div className={`result-detail ${open === index ? "expanded" : ""}`}><div><p className={result.status === "pass" ? "why-fit" : "why-fail"}>{result.status === "pass" ? <Check size={14} /> : "NO —"} {result.why}</p>{result.status === "pass" && <Link className="text-link" href="/plan">ADD TO PLAN <ArrowRight size={14} /></Link>}</div></div></div><div className="result-status"><StatusPill status={result.status} reason={result.reason} /><button className="see-why" onClick={() => setOpen(open === index ? null : index)} aria-expanded={open === index}> {open === index ? "HIDE" : "SEE WHY"} <ArrowRight size={13} /></button></div></GlowCard></Reveal>)}</div><div className="discover-footer"><span>THE GATE IS ALWAYS ON</span><span className="line" /><span>REAL CONSTRAINTS · REAL ANSWERS</span></div></div><PageFooter /></AppShell> }
