"use client"

import { useState } from "react"
import { ArrowLeft, ArrowRight, CalendarDays, MapPin, RefreshCw, Clock3 } from "lucide-react"
import { AppShell, CrossFade, EmptyState, GlowCard, Reveal, StatusPill, PageFooter } from "@/components/travel-ui"

const baseDays = [{ day: "DAY 01", date: "SAT 17 AUG", title: "The city, at an unhurried pace", items: [{ time: "16:10", title: "Leave Bandra", copy: "A short walk to the sea wall. No car required." }, { time: "17:00", title: "Bandra Fort", copy: "Golden-hour views with enough time to sit down." }, { time: "19:20", title: "Dinner at The Table", copy: "Reservation held. 18 minutes from the fort." }] }]
const alternateDays = [{ ...baseDays[0], title: "The city, after the rain", items: [{ time: "16:30", title: "Leave Bandra", copy: "Traffic has eased. A calm route through the side streets." }, { time: "17:20", title: "Kala Ghoda", copy: "Indoor galleries replace the exposed fort route." }, { time: "19:20", title: "Dinner at The Table", copy: "Reservation held. The plan still protects your evening." }] }]

export default function PlanPage() { const [version, setVersion] = useState("base"); const days = version === "base" ? baseDays : alternateDays; return <AppShell><div className="app-page"><div className="app-topline"><a href="/discover"><ArrowLeft size={14} /> DISCOVERY</a><span>PLAN / 01</span><a href="/plan/chat">ASK BUDDY <ArrowRight size={14} /></a></div><Reveal><div className="plan-intro"><div><p className="eyebrow">YOUR DAY, HELD LIGHTLY</p><h1>One good<br /><i>afternoon.</i></h1><p>Built around your 2h 40m window, your pace, and the reservation you already made.</p></div><GlowCard className="fit-summary"><StatusPill status="pass" /><strong>Everything still fits</strong><span>Last checked moments ago</span></GlowCard></div></Reveal><div className="plan-layout"><section className="timeline"><div className="timeline-heading"><span>ITINERARY</span><span>17 AUG / MUMBAI</span></div><CrossFade itemKey={version}>{days.map(day => <div className="day-group" key={day.day}><div className="day-label"><CalendarDays size={15} /> <span>{day.day}</span><small>{day.date}</small></div>{day.items.map(item => <GlowCard key={item.time} className="timeline-row"><time>{item.time}</time><div><h2>{item.title}</h2><p>{item.copy}</p></div><MapPin size={15} /></GlowCard>)}</div>)}</CrossFade></section><aside className="plan-aside"><GlowCard className="replan-card"><p className="eyebrow">LIVE FIT CHECK</p><h2>Weather shifted.</h2><p>The fort is still possible, but this alternate keeps the same dinner and removes the exposed walk.</p><button className="outline-button" onClick={() => setVersion(version === "base" ? "alternate" : "base")}><RefreshCw size={14} /> {version === "base" ? "SHOW ALTERNATE" : "RESTORE ORIGINAL"}</button></GlowCard><GlowCard className="detail-card"><Clock3 size={16} /><span>BUFFER</span><strong>28 minutes</strong><p>Enough room to stop without breaking the plan.</p></GlowCard></aside></div></div><PageFooter /></AppShell> }
